# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui_login.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Login(object):
    def setupUi(self, Login):
        Login.setObjectName("Login")
        Login.resize(454, 495)
        font = QtGui.QFont()
        font.setPointSize(16)
        Login.setFont(font)
        Login.setToolButtonStyle(QtCore.Qt.ToolButtonTextOnly)
        Login.setDocumentMode(False)
        Login.setTabShape(QtWidgets.QTabWidget.Rounded)
        self.centralwidget = QtWidgets.QWidget(Login)
        self.centralwidget.setObjectName("centralwidget")
        self.lblLogin = QtWidgets.QLabel(self.centralwidget)
        self.lblLogin.setGeometry(QtCore.QRect(150, 20, 181, 31))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(20)
        self.lblLogin.setFont(font)
        self.lblLogin.setObjectName("lblLogin")
        self.lblCorreo = QtWidgets.QLabel(self.centralwidget)
        self.lblCorreo.setGeometry(QtCore.QRect(60, 100, 131, 31))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(16)
        self.lblCorreo.setFont(font)
        self.lblCorreo.setObjectName("lblCorreo")
        self.btnIngresar_login = QtWidgets.QPushButton(self.centralwidget)
        self.btnIngresar_login.setGeometry(QtCore.QRect(60, 330, 161, 51))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(16)
        self.btnIngresar_login.setFont(font)
        self.btnIngresar_login.setStyleSheet("")
        self.btnIngresar_login.setObjectName("btnIngresar_login")
        self.btnRegistarse = QtWidgets.QPushButton(self.centralwidget)
        self.btnRegistarse.setGeometry(QtCore.QRect(240, 330, 161, 51))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(16)
        self.btnRegistarse.setFont(font)
        self.btnRegistarse.setStyleSheet("")
        self.btnRegistarse.setObjectName("btnRegistarse")
        self.lblContrasena = QtWidgets.QLabel(self.centralwidget)
        self.lblContrasena.setGeometry(QtCore.QRect(60, 200, 171, 31))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(16)
        self.lblContrasena.setFont(font)
        self.lblContrasena.setObjectName("lblContrasena")
        self.txtcorreo_login = QtWidgets.QLineEdit(self.centralwidget)
        self.txtcorreo_login.setGeometry(QtCore.QRect(60, 140, 331, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.txtcorreo_login.setFont(font)
        self.txtcorreo_login.setStyleSheet("")
        self.txtcorreo_login.setObjectName("txtcorreo_login")
        self.txtcontrasena_login = QtWidgets.QLineEdit(self.centralwidget)
        self.txtcontrasena_login.setGeometry(QtCore.QRect(60, 250, 331, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.txtcontrasena_login.setFont(font)
        self.txtcontrasena_login.setStyleSheet("")
        self.txtcontrasena_login.setObjectName("txtcontrasena_login")
        Login.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(Login)
        self.statusbar.setObjectName("statusbar")
        Login.setStatusBar(self.statusbar)

        self.retranslateUi(Login)
        QtCore.QMetaObject.connectSlotsByName(Login)

    def retranslateUi(self, Login):
        _translate = QtCore.QCoreApplication.translate
        Login.setWindowTitle(_translate("Login", "Log In"))
        self.lblLogin.setText(_translate("Login", "LOG IN"))
        self.lblCorreo.setText(_translate("Login", "Correo"))
        self.btnIngresar_login.setText(_translate("Login", "Ingresar"))
        self.btnRegistarse.setText(_translate("Login", "Registrarse"))
        self.lblContrasena.setText(_translate("Login", "Contraseña"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Login = QtWidgets.QMainWindow()
    ui = Ui_Login()
    ui.setupUi(Login)
    Login.show()
    sys.exit(app.exec_())
