# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui_nuevatarea.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_NuevaTarea(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(395, 565)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.txtDescripcion = QtWidgets.QTextEdit(self.centralwidget)
        self.txtDescripcion.setGeometry(QtCore.QRect(40, 260, 311, 201))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.txtDescripcion.setFont(font)
        self.txtDescripcion.setObjectName("txtDescripcion")
        self.lblNuevaTarea = QtWidgets.QLabel(self.centralwidget)
        self.lblNuevaTarea.setGeometry(QtCore.QRect(40, 30, 221, 31))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(16)
        self.lblNuevaTarea.setFont(font)
        self.lblNuevaTarea.setObjectName("lblNuevaTarea")
        self.lblDescripcion = QtWidgets.QLabel(self.centralwidget)
        self.lblDescripcion.setGeometry(QtCore.QRect(40, 210, 191, 31))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(16)
        self.lblDescripcion.setFont(font)
        self.lblDescripcion.setObjectName("lblDescripcion")
        self.txtNuevatarea = QtWidgets.QLineEdit(self.centralwidget)
        self.txtNuevatarea.setGeometry(QtCore.QRect(40, 80, 311, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.txtNuevatarea.setFont(font)
        self.txtNuevatarea.setObjectName("txtNuevatarea")
        self.btnGuardar = QtWidgets.QPushButton(self.centralwidget)
        self.btnGuardar.setGeometry(QtCore.QRect(40, 480, 151, 51))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(16)
        self.btnGuardar.setFont(font)
        self.btnGuardar.setObjectName("btnGuardar")
        self.btnCancelar = QtWidgets.QPushButton(self.centralwidget)
        self.btnCancelar.setGeometry(QtCore.QRect(210, 480, 151, 51))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(16)
        self.btnCancelar.setFont(font)
        self.btnCancelar.setObjectName("btnCancelar")
        self.cmbClasificacion = QtWidgets.QComboBox(self.centralwidget)
        self.cmbClasificacion.setGeometry(QtCore.QRect(40, 140, 311, 41))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.cmbClasificacion.setFont(font)
        self.cmbClasificacion.setObjectName("cmbClasificacion")
        self.cmbClasificacion.addItem("")
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Nueva Tarea"))
        self.lblNuevaTarea.setText(_translate("MainWindow", "Nueva tarea"))
        self.lblDescripcion.setText(_translate("MainWindow", "Descripcion"))
        self.btnGuardar.setText(_translate("MainWindow", "Guardar"))
        self.btnCancelar.setText(_translate("MainWindow", "Cancelar"))
        self.cmbClasificacion.setItemText(0, _translate("MainWindow", "Clasificacion"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_NuevaTarea()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
